### PR TITLE
Add const to processing inputs in all examples

### PR DESCRIPTION
**Pull request by ssaue**
## What is the goal of this PR?

The PR enables processing of const data containers by explicitly declaring input data as const (not only as const pointers). This is an interface change only, since there is no non-const access to these inputs internally.

## What are the changes implemented in this PR?

Input parameters to all processing calls in the examples are defined as `const float** const inputs`

### CODE REVIEW

**Comment by leomccormack** [comment]
Hey! I guess this is maybe a matter of style.

E.g. the SPARTA VST plugins interface with the examples using the same pointers for the input and output, which I think is quite tidy:
https://github.com/leomccormack/SPARTA/blob/master/audio_plugins/_SPARTA_ambiBIN_/src/PluginProcessor.cpp
`ambi_bin_process(hAmbi, pFrameData, pFrameData, nNumInputs, nNumOutputs, frameSize);`

Changing the SPARTA code to have dedicated read (const) and write (non-const) pointers is of course an option, but since all of the examples employ intermediate internal buffers, either way is safe. Having the const just means some extra code is needed. 

Was there a specific reason for making these const? 

Would adding the following doxygen comment to the _process() functions clear any confusion?:
"@note This example employs intermediate internal buffers. Therefore, it is also safe if the 'input' buffer pointers are the same as the 'output' buffer pointers."

**Comment by ssaue** [comment]
Hi! First of all, I wrongly assumed that you still could call `ambi_bin_process` as you showed above. So I realize my PR would cause changes in SPARTA code. I have another suggestion, and will return to that at the end.

Secondly, my use case it that we have our own set of processing modules with a virtual c++ interface similar to `process(const std::vector<float> input, std::vector<float>& output)`. The const input argument is there to prevent anyone from modifying the input vector. Now, if we in one of our modules want to call `ambi_bin_process` with the data pointer from the input vector, we have to make a non-const copy of the vector first. Since you do that same copy within `ambi_bin_process` it seems like a waste. The current example interfaces are de facto implemented as if the input argument is const, but does not enforce it in the interface.

However, there is a third solution that my satisfy both requirements: `const float* const * inputs` can be called with both `const float**` and `float**`. Could that be an acceptable solution instead?

**Comment by leomccormack** [comment]
Ah OK. So actually:
`const float* const * inputs` 
Since this works with the current SPARTA way of interfacing (shared input/output pointer), if it also extends the usability with  your way?, then its fine by me : )

**Comment by ssaue** [comment]
Excellent. I will update the PR with the revised signature and let you have another look.

**Comment by ssaue** [comment]
The PR has been updated with the revised signature that supports both the SPARTA case (shared input/output buffers) and my C++ case where the input is derived from const containers.

**Comment by leomccormack** [comment]
thanks!

**Pull request merged**
